### Post request to create new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Datsdf Dang",
  "email": "testmai123456l@gfdfasfmail.com",
  "address": "Somewhere in the world",
  "dateOfBirth": "2000-10-30",
  "registerDate": "2000-10-30"
}

###